### ISSUE TITLE
only 1/3 of the screen shows on native monitor when multiple monitors are attached

### ISSUE THREAD

**Issue by hyperlink** [marczak/johnnynash#1]
Hello!

Thanks for writing this screensaver. I have two external monitors attached to my macbook and when the screensaver activates the native macbook monitor's screen only displays 1/3 of the screen. The rest of the screen is gray or black.

On Retina, 13-inch, Late 2013 running OS X 10.9.3.

**Comment by marczak** [comment]
Yes - you are correct. I'll set about to make this work properly with multiple monitors.

**Comment by marczak** [comment]
Just updated, and working in my tests with two and three monitor configs. Can you please verify with the latest commits?

**Comment by hyperlink** [comment]
I would be glad to test this. Do you have a compiled build? I'm not a mac developer.

**Comment by dannyman** [comment]
Thank you for this software, @marczak !

I do not have this problem.  I have a retina display, a 4k display, and another display ... when screen lock is activated, I can see the retina display on the MBP.  The external displays go black.

**Comment by marczak** [comment]
Hey, @dannyman - I'm happy to look into this. Can you please open a new, separate issue for it? Thanks.
